#!/usr/bin/env python3

###################################################################################
#                                                                                 #
#  Monte Carlo Particle Lists : MCPL                                              #
#                                                                                 #
#  Application providing the pymcpltool. This actually just means importing the   #
#  mcpl.py module and running the main() function found there.                    #
#                                                                                 #
#  Find more information and updates at https://mctools.github.io/mcpl/           #
#                                                                                 #
#  This file can be freely used as per the terms in MCPLExport/license.txt.       #
#                                                                                 #
#  Written by Thomas Kittelmann, 2017.                                            #
#                                                                                 #
###################################################################################

#Import mcpl module (with a fall-back sys.path edit, so the tool can be run
#from an MCPL installation even though the user did not set PYTHONPATH correctly):
try:
    import MCPL
except ImportError:
    import sys, os
    try:
        sys.path.insert(0,os.path.join(os.path.dirname(__file__)))
        import MCPL
    except ImportError:
        sys.path.insert(0,os.path.join(os.path.dirname(__file__),'..','share','MCPL','python'))
        import MCPL

#Launch tool:
MCPL.main()
