#!/usr/bin/env bash
set -eu
#Reduce statistics and physics list for unit test:
cat `which sb_skeletonsp_scan` | sed 's#100000#1000#' | sed 's#QGSP_BIC_HP_EMZ#QGSP_BIC_HP#' > ./sb_skeletonsp_scan_edited
chmod +x ./sb_skeletonsp_scan_edited
./sb_skeletonsp_scan_edited -qlocal -j2 -d ./my_scanresults --launch --halt-on-error
SIMPLEHISTS_OVERLAY_FORCE_SAVEFILE=1 sb_skeletonsp_scanana ./my_scanresults

