name: 'setup'
description: 'Setup conda environment for simplebuild_dgcode'
inputs:
  PYTHON_VERSION:
    description: Python version to set up
    type: string
    default: '3.11'
  CACHED_NOARCH_DEF_PY_FILE:
    description: Path to cached_noarch_definitions.py
    type: string
    required: true
  CONDA_ENV_FILE:
    description: Path to conda .yml file
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        activate-environment: simplebuild_dgcode

    - name: Retrieve cached Geant4 data packages
      id: cache-geant4-data-packages
      uses: actions/cache@v3
      with:
        path: ~/my-geant4-data-cache
        key: geant4-data-packages

    - name: Install Geant4 data packages
      if: steps.cache-geant4-data-packages.outputs.cache-hit != 'true'
      run: |
        python3 ${NOARCHDEFPYFILE} --yml > ~/cached_noarch_definitions.yml
        conda config --show pkgs_dirs
        conda config --remove-key pkgs_dirs
        conda config --show pkgs_dirs
        conda config --add pkgs_dirs ~/my-geant4-data-cache
        conda config --show pkgs_dirs
        conda env create -n geant4data -f ~/cached_noarch_definitions.yml
        #mkdir -p ~/my-geant4-data-cache/noarch && cp -r ~/conda_pkgs_dir/*.conda ~/my-geant4-data-cache/noarch/
        #mkdir -p ~/my-geant4-data hest-cache/noarch && cp -r ~/conda_pkgs_dir/*.conda ~/my-geant4-data-cache/noarch/
      shell: bash -l {0}
      env:
        CONDA_SOLVER: libmamba
        NOARCHDEFPYFILE: ${{ inputs.CACHED_NOARCH_DEF_PY_FILE }}

    - name: DEBUG list dir content
      run: ls -l ~/my-geant4-data-cache
      shell: bash

    - name: Set Geant4 data packages source
      if: steps.cache-geant4-data-packages.outputs.cache-hit == 'true'
      run: conda config --add pkgs_dirs ~/my-geant4-data-cache
      #run: conda config --add channels file://~/my-geant4-data-cache
      shell: bash -l {0}
      env:
        CONDA_SOLVER: libmamba

    - name: Update conda-setup.yml with python version
      run: |
        set -eux
        test -f ${CONDA_ENV_FILE}
        cat ${CONDA_ENV_FILE} | sed "s/python/python=${{ inputs.PYTHON_VERSION }}/g" > actualenv.yml
        cat actualenv.yml
      shell: bash
      env:
        CONDA_ENV_FILE: ${{ inputs.CONDA_ENV_FILE }}

    - name: Setup simplebuild_dgcode environment
      run: |
        conda config --show pkgs_dirs
        conda env update --verbose -n simplebuild_dgcode -f actualenv.yml
      shell: bash -el {0}

    - name: Verify that Geant4 data packages match the cached versions
      run: python3 ${NOARCHDEFPYFILE} --verify-usage
      shell: bash -el {0}
      env:
        CONDA_SOLVER: libmamba
        NOARCHDEFPYFILE: ${{ inputs.CACHED_NOARCH_DEF_PY_FILE }}

    - name: Conda list
      run: |
        which python3
        python3 --version
        which cmake
        cmake --version
        conda info
        conda list
      shell: bash -el {0}
