name: dgcodeenviron
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - tomli
  - pybind11 >= 2.10.4
  - cmake >=3.24.2
  - compilers
  - numpy
  - bash
  - pip
  # - git
  - ncrystal
  - matplotlib
  - zlib
  - geant4
  - expat
  - openscenegraph
  - ase
  - pymatgen
  # - gemmi
  - spglib
  - scipy
  - pandas
  - hdf5
