#!/usr/bin/env bash
#set language vars to not get uniq -c to barf on osx:
export LC_CTYPE=C
export LANG=C
sb_griffdrwtests_sim npoints=900 -lPL_Empty -mFULL
if [ $? != 0 ]; then
    exit 1
fi
sb_griffformat_dumpfile -u grifftests.griff
if [ $? != 0 ]; then
    exit 1
fi
sb_griffdrwtests_ana grifftests.griff|uniq -c
