#autogenerated file
__doc__='python module for package G4PhysicsLists'
from . _init import _get_lists as _cpp_get_lists

def getAllListNames(include_description = False, include_base = True, include_custom = True):
    base=[]
    custom=[]
    if include_base:
        base = _cpp_get_lists( include_description, True, False )
    if include_custom:
        custom = _cpp_get_lists( include_description, False, True )
    return sorted(base)+sorted(custom)

def listIsCustom(plname):
    return plname.startswith('PL_')

def printAvailableLists():
    print ("Available physics lists (append +TS or +OPTICAL to inject thermal scattering / optical processes):")
    for l,descr in getAllListNames(include_description=True):
        print ("   %s [%s]"%(l,descr))
