#!/usr/bin/env python3
from __future__ import print_function
import sys
if not sys.stdin.isatty():
    for l in sorted(sys.stdin.readlines()):
        print (l,end='')
else:
    print ('This script must be used in a pipe')
    sys.exit(1)
