name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - bash
  - simple-build-dgcode >= 1.3.0
  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  - geant4>=11.1.3,<11.2.0
  - geant4-data-ndl=4.7.0
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui<5 #v5 is no longer open source
  - pip
