name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - bash
  - simple-build-dgcode >= 1.3.3
  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  #Need to avoid python 3.12 due to conda pkg issues
  - python>=3.10.0,<3.12
  - geant4=11.2.2
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
