name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - compilers
  - bash
  - simple-build-dgcode >= 1.1.0
  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  - geant4 >= 11.1.3
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
