#!/usr/bin/env bash
echo "This will cancel all your (running or pending) jobs in the queue."
echo -n "If you are sure, type \"yes\": "
read REP
if [ "x$REP" = "xyes" ] ; then
    echo "Cancelling all jobs for user $USER"
    scancel -u $USER
else
    echo "Abort."
fi
