#!/usr/bin/env bash
sb_g4mcpltests_mcplwrite |sed 's#'"${G4NEUTRONHPDATA}"'#<G4NEUTRONHPDATA>#'
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi
mcpltool -j target.mcpl.gz && mcpltool -j recordfwd.mcpl.gz
