#!/usr/bin/env python3

import G4GriffGen.GriffGen as Gen
gen = Gen.create()
gen.input_file = 'G4GriffGenTests/exampleinput_10similarevts.griff'

import G4StdGeometries.GeoEmptyWorld as Geo
geo = Geo.create()

import G4Launcher
launcher = G4Launcher(geo,gen)
launcher.setPhysicsList('PL_Empty')
import sys
if len(sys.argv)>1:
  launcher.go()
else:
  launcher.cmd_postinit('/tracking/verbose 3')
  launcher.startSimulation(0)


