#!/usr/bin/env bash
sb_generatorexamples_custompygen_inline -lPL_Empty|grep G4Launcher|grep -v '\[seed .*\]'
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi
sb_generatorexamples_custompygen_module -lPL_Empty|grep G4Launcher|grep -v '\[seed .*\]'
if [ ${PIPESTATUS[0]} != 0 ]; then
    exit 1
fi
