#!/usr/bin/env bash
set -e
set -o pipefail
sb_g4utils_g4logsanitiser sb_g4tests_datacollect_cpp 15 testoutput_reduced.griff 1 REDUCED |grep -v 'G4Launcher:: Begin simulation of event'
sb_griffformat_info testoutput_reduced.griff |grep -v 'Total \['

