#!/usr/bin/env bash
set -e
set -o pipefail
sb_g4utils_g4logsanitiser sb_g4tests_datacollect -m FULL -o testoutput_full.griff -n 10 |grep -v 'G4Launcher:: Begin simulation of event'
sb_griffformat_info testoutput_full.griff |grep -v 'Total \['

