name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
#The preceding line will be edited for python version in
#.github/workflows/condatest.yml The rest should match
#<reporoot>/resources/conda_dgcode.yml except that simple-build-dgcode itself
#should be left out (and replaced with simple-build-system).
  - compilers
  - bash
  - simple-build-system>=1.2.6
#fixme: like this for now:  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  - geant4>=11.1.3,<11.2.0
#  - geant4-data-ndl=4.7.0
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
