name: dgcode
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
#The preceding line will be edited for python version in
#.github/workflows/condatest.yml The rest should match
#<reporoot>/resources/conda_dgcode.yml except that simple-build-dgcode itself
#should be left out (and replaced with simple-build-system).
  - compilers
  - bash
  - simple-build-system
  - ncrystal
  - mcpl
  - matplotlib
  - zlib
  - geant4 >= 11.1.3
  - expat
  - openscenegraph
  - scipy
  - hdf5
  - pysimplegui
  - pip
