name: publish-doc-condaenv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - simple-build-system>=1.1.0
  - compilers
  - bash
  - zlib
  - sphinx>=7.2.6
  - sphinx_rtd_theme>=1.3.0
  - sphinx-argparse
#  - sphinx-toolbox
  - pip
  - pip:
#    -  git+https://github.com/sphinx-toolbox/sphinx-licenseinfo
#    - sphinx-argparse
    - sphinx-toolbox
#    - sphinx-licenseinfo
