name: test-essncrystaldev-tkvolatile
on:
  workflow_dispatch:
    inputs:
      manual-debugging:
        type: boolean
        description: Launch manual debugging tmate session on failure
        default: false
      longtests:
        type: boolean
        description: Include NCLongxxx tests
        default: false

jobs:

  build:
    strategy:
      #fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, CC: gcc,      CXX: g++,        python: '3.12' }
          - { os: macos-latest,  CC: clang,    CXX: clang++,    python: "3.11" }
    name: ${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CONDA_SOLVER: libmamba

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./src_co

      - name: Checkout project repo
        env: # Or as an environment variable
          THEACCESSTOKEN: ${{ secrets.ACCESS_TOKEN_NCRYSTALDEV }}
        run: |
          set -eu
          test "${THEACCESSTOKEN:-}" != "" || ( echo "Access token missing"; exit 1 )
          git clone -b tk_volatile --depth=1 'https://usernamedoesnotmatter:'"${THEACCESSTOKEN}"'@git.esss.dk/ncrystal/ncrystaldev.git' ./src_testproject

      - name: Setup conda environment
        uses: ./src_co/.github/actions/setup
        with:
          PYTHON_VERSION: ${{ matrix.python }}
          USE_MAMBA: true
          CACHED_NOARCH_DEF_PY_FILE: ./src_co/.github/resources/cached_noarch_definitions.py
          CONDA_ENV_FILE : ./src_co/.github/resources/conda-setup.yml

      - name: Install
        run: |
          set -eu
          #For dev work: python3 -m pip install git+https://github.com/mctools/simplebuild@whateverbranchname
          #For dev work: python3 -m pip install --no-deps ./src_co
          python3 -m pip install --no-deps ./src_co
          echo "sb --version: "$(sb --version)

      #NCrystal needs extra packages:
      - name: Install extra conda pkgs
        run: conda install --yes mpmath spglib gemmi ase pymatgen

      - name: Build (release mode)
        id: build-release-mode
        run: |
          set -eu
          cd src_testproject
          sb

      - name: Launch short unit tests (release mode)
        id: test-release-mode-short
        run: |
          set -eu
          cd src_testproject
          sb -t --testexcerpts=100 --requirepkg=DGCodeRecommended,NCUtils,NCG4,NCTests,NCThreadVal,NCPerfVal --testfilter='!sb_nclong*'

      - name: Launch long unit tests (release mode)
        id: test-release-mode-long
        if: inputs.includelongtests == true
        run: |
          set -eu
          cd src_testproject
          sb -t --testexcerpts=100 --requirepkg=DGCodeRecommended,NCUtils,NCG4,NCTests,NCThreadVal,NCPerfVal --testfilter='sb_nclong*'

      - name: Setup tmate session for manual debugging
        uses: mxschmitt/action-tmate@v3
        if: always() && inputs.manual-debugging == true && (steps.test-release-mode-short.outcome != 'success' || steps.test-release-mode-long.outcome != 'success')
        with:
          limit-access-to-actor: true
