#!/usr/bin/env bash
prog=`which $1`
if [ $? != 0 ]; then
    echo "Error: Command not found: $1"
    exit 1
fi
shift 1
export PYTHONMALLOC=malloc
valgrind --tool=memcheck --track-origins=yes --malloc-fill=0x80 --free-fill=0x7f --suppressions=$SBLD_DATA_DIR/DevTools/valgrind_suppressions.txt --trace-children=yes $prog "$@"

